controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
profil: 
    path : /profil/
    controller : App\Controller\ProfilController::index
    
notification:
    path: /notification/
    controller : App\Controller\NotificationController:index

notes:
    path: /notes
    controller: App\Controller\NoteController::index

note_participants:
    path: /note_participants/{trajetId}
    controller: App\Controller\NoteController::loadParticipants
    methods: [GET]
