controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

profil: 
    path : /profil
    controller : App\Controller\ProfilController::editProfile

editmdp: 
    path : /profil 
    controller : App\Controller\ProfilController::editPassword